[phases.setup]
nixPkgs = ["nodejs_22", "corepack"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm start"
